### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by greggles** [mr-internetix/vcard-qr-code-generator#1]
Hello,

I was looking for a page to create a QRCode of a VCard and found a ton of ways to do it that:
* Required paying
* Held the VCard information server-side
* Seemed sketchy like they might steal info

It took me a while to figure out that this app is deployed from Github to the heroku page at https://vcard-qr-code.herokuapp.com/

This tool is so wonderful! 2 bits of documentation inside a README file could really help it:

1. Document how to run the express app, for those who wish to do so.
2. Add a link to the [Heroku demo page](https://vcard-qr-code.herokuapp.com/)

**Comment by mr-internetix** [comment]
Taking things into consideration i will try to do it in 2-3 days thanks for drawing out attention over these key points 


Really appreciated 👍

**Comment by mr-internetix** [comment]
Done , thanks @greggles

**Comment by greggles** [comment]
The README seems perfect to me. Thanks again for the repo and for that improvement!

**Comment by mr-internetix** [comment]
My pleasure
